// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-RLucw7E2e6NDk317Q0-dT00O5vW4MD8',
    appId: '1:49341591771:web:12c75c069a657ec6a39cfe',
    messagingSenderId: '49341591771',
    projectId: 'drinks-af0e7',
    authDomain: 'drinks-af0e7.firebaseapp.com',
    storageBucket: 'drinks-af0e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7UaojLan9kAsoCO5sasEepC6cWk3Hm88',
    appId: '1:49341591771:android:43526f26fec2395ba39cfe',
    messagingSenderId: '49341591771',
    projectId: 'drinks-af0e7',
    storageBucket: 'drinks-af0e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcN0M-6XyVRFLd5EwTV5e1YBYyyv3wb34',
    appId: '1:49341591771:ios:0d4b9b89f35bca78a39cfe',
    messagingSenderId: '49341591771',
    projectId: 'drinks-af0e7',
    storageBucket: 'drinks-af0e7.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcN0M-6XyVRFLd5EwTV5e1YBYyyv3wb34',
    appId: '1:49341591771:ios:0d4b9b89f35bca78a39cfe',
    messagingSenderId: '49341591771',
    projectId: 'drinks-af0e7',
    storageBucket: 'drinks-af0e7.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-RLucw7E2e6NDk317Q0-dT00O5vW4MD8',
    appId: '1:49341591771:web:b1ac57cfd78af7cba39cfe',
    messagingSenderId: '49341591771',
    projectId: 'drinks-af0e7',
    authDomain: 'drinks-af0e7.firebaseapp.com',
    storageBucket: 'drinks-af0e7.firebasestorage.app',
  );

}